@ArasERP_HostAddress = http://localhost:5178

GET {{ArasERP_HostAddress}}/health
Accept: application/json

### Search Address - Jakarta
GET {{ArasERP_HostAddress}}/api/addresses/search?keyword=jakarta
