@ArasERP_HostAddress = http://localhost:5178/api


### Create Stock Items
POST {{ArasERP_HostAddress}}/stock-items
Content-Type: application/json

{
    "name": "Jiancare Qianpross",
    "sku": "jcr-qp",
    "unit": "pcs",
    "costingMethod": "FIFO"
}

### List Stock Items
GET {{ArasERP_HostAddress}}/stock-items
Accept: application/json

### List Stock Items for a warehouse
GET {{ArasERP_HostAddress}}/stock-items?warehouseId=<warehouse-id>
Accept: application/json
